---
- block:
    - name: Ensure EPEL package provides openscap scanner command is installed
      package:
        name: "{{ sovc_epel_repo_rpm }}"
        # .. note:: Avoid 'latest' because it may cause change.
        state: present

    - name: Ensure pandoc is installed
      package:
        name: pandoc
        # .. note:: Avoid 'latest' because it may cause change.
        state: present
  when:
    - sovc_covnert_html_to_md

- name: Ensure package provides openscap scanner command is installed
  package:
    name: "{{ sovc_scan_pkg }}"
    # .. note:: Avoid 'latest' because it may cause change.
    state: present

- block:
    - name: Ensure the scanner command can run
      command: >-
        oscap -V
      changed_when: false
      register: __result

    - name: Debug the output of the previous command, the scanner could run
      debug:
        var: __result
  when:
    - sovc_debug

- name: Fetch security reference data
  get_url:
    url: "{{ sovc_security_reference_data_url }}"
    dest: "{{ sovc_security_reference_data_name }}"

# vim:sw=2:ts=2:et:
